version: '3.1'
services:
  agent-3:
    image: zabbix/zabbix-agent:alpine-3.2-latest
    ports:
      - 10050:10050
    deploy:
      placement:
        constraints:
          - node.hostname == node-3
    environment:
      ZBX_HOSTNAME: 'node-3'
      ZBX_SERVER_HOST: server
      ZBX_PASSIVESERVERS: '[::]'
      #ZBX_ACTIVESERVERS: server:10051
    depends_on:
      - server
