version: '3.1'
services:
  server:
    image: zabbix/zabbix-server-mysql:alpine-3.2-latest
    environment:
      DB_SERVER_HOST: '10.20.60.3'
      MYSQL_DATABASE: 'demo_zabbix'
      MYSQL_USER: root
      MYSQL_PASSWORD: 111
    ports:
      - 10051:10051
