version: '3.1'
services:
  web:
    image: zabbix/zabbix-web-nginx-mysql
    environment:
      ZBX_SERVER_HOST: '10.20.60.3'
      DB_SERVER_HOST: '10.20.60.3'
      MYSQL_DATABASE: 'demo_zabbix'
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      PHP_TZ: 'Asia/Shanghai'
    ports:
      - 80:80
    depends_on:
      - server
