version: '3.1'
services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - "/mnt/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 111
  adminer:
    image: adminer
    ports:
        - 3080:8080
